apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-etc-hosts
data:
  hosts: |
    192.168.1.1 renoir.axyus.com
---
apiVersion: v1
kind: Pod
metadata:
  name: moninginx
spec:
  initContainers:
  - name: modif-hosts
    image: busybox
    command:
    - sh
    - -c
    - "echo '192.168.1.1 renoir.axyus.com' >> /etc/hosts"
    volumeMounts:
    - name: hosts
      mountPath: /tmp/hosts
      subPath: hosts
  containers:
  - name: moninginx
    image: nginx
    ports:
    - containerPort: 80
  volumes:
  - name: hosts
    configMap:
      name: cm-etc-hosts

