apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-etc-hosts
  namespace: etc-hosts
data:
  hosts: |
    192.168.1.1 renoir.axyus.com
---
apiVersion: v1
kind: Pod
metadata:
  name: moninginx
  namespace: etc-hosts
spec:
  initContainers:
  - name: modif-hosts
    image: busybox
    command:
    - sh
    - -c
    - "cat /tmp/hosts >> /etc/hosts"
    volumeMounts:
    - name: hosts
      mountPath: /tmp
  containers:
  - name: moninginx
    image: nginx
    ports:
    - containerPort: 80
  volumes:
  - name: hosts
    configMap:
      name: cm-etc-hosts

